const hotelData = [
    {
        id: 'hotel1',
        name: 'Cantho Eco Resort',
        layoutPrice: '944,444 VND',
        roomType: [
            { roomId: "hotel1_room1", name: 'Single bed room', price: '950,000 VND' },
            { roomId: "hotel1_room2", name: 'Double bed room', price: '1,500,000 VND' },
            { roomId: "hotel1_room2", name: 'Family room', price: '3,000,000 VND' }
        ],
        mainImage: '../images/Hotel img/CanthoEcoResort/CanthoEcoResort.jpeg',
        layoutAddress: "Phong Dien, CanTho",
        utilities: ['Free cancellation',
            'No prepayment needed',
            'Late escape deal'],
        modalImages: [
            '../images/Hotel img/CanthoEcoResort/CanthoEcoResort_sub1.jpg',
            '../images/Hotel img/CanthoEcoResort/CanthoEcoResort_sub2.jpg',
            '../images/Hotel img/CanthoEcoResort/CanthoEcoResort_sub3.jpg',
            '../images/Hotel img/CanthoEcoResort/CanthoEcoResort_sub4.jpg'
        ],
        description: "Get your trip off to a great start with a stay at this property, which offers free Wi-Fi in all rooms. \n                              Conveniently situated in the Cai Rang part of Cần Thơ, this property puts you close to attractions and \n                              interesting dining options. Don't leave before paying a visit to the famous Ong Temple. Rated with 4 stars, \n                              this high-quality property provides guests with access to restaurant and sauna on-site.",
        address: 'Km7, National Highway 61C, Nhon Nghia Commue, Phong Dien District, Can Tho, Vietnam',
        lat: 9.95913,
        long: 105.68892,
        point: '8.7',
        popularity: 'Fabulous',
        reviews: '111',
        facilities: [
            `<i class="fas fa-swimmer"></i> Outdoor swimming pool`,
            `<i class="fas fa-wifi"></i> Free wifi`,
            `<i class="fas fa-spa"></i> Spa and wellness centre`,
            `<i class="fas fa-parking"></i> Free parking`,
            `<i class="fas fa-utensils"></i> Restaurant`,
            `<i class="fas fa-dumbbell"></i> Fitness centre`,
            `<i class="fas fa-glass-martini-alt"></i> Bar`,
            `<i class="fas fa-coffee"></i> Fabulous breakfast`
        ],
        facebook: 'https://www.facebook.com/canthoecoresort',
        website: 'https://www.facebook.com/canthoecoresort',
        phone: 'tel: +84292 6295 999',
        mail: 'mailto: marketing@canthoecoresort.com'
    },
    {
        id: 'hotel2',
        name: 'Sheraton Hotel',
        layoutPrice: '1,800,000 VND',
        roomType: [
            { roomId: "hotel2_room1", name: 'Single bed room', price: '950,000 VND' },
            { roomId: "hotel2_room2", name: 'Double bed room', price: '1,500,000 VND' },
            { roomId: "hotel2_room3", name: 'Family room', price: '3,000,000 VND' }
        ],
        mainImage: '../images/Hotel img/Sheraton/Sheraton.jpg',
        layoutAddress: "Ninh Kieu, CanTho",
        utilities: ['Free cancellation', 'No prepayment needed'],
        modalImages: [
            '../images/Hotel img/Sheraton/Sheraton_sub1.jpg',
            '../images/Hotel img/Sheraton/Sheraton_sub2.jpg',
            '../images/Hotel img/Sheraton/Sheraton_sub3.jpg',
            '../images/Hotel img/Sheraton/Sheraton_sub4.jpg'
        ],
        description: 'Luxurious riverside hotel with stunning views, full-service spa, gym with hot tub and sauna, outdoor pool. Conveniently located near Ninh Kieu pier. \n                                Perfect base for exploring city attractions and enjoying a delightful stay. Conveniently located in City Center, Cần Thơ, this property offers easy \n                                access to vibrant markets, charming cafes, and popular attractions like Ninh Kieu Wharf, Ong Temple, and Quang Duc Pagoda. Enjoy exclusive amenities \n                                such as breakfast, a pool, and a steam room. The luxurious rooms feature air conditioning, in-room safe, complimentary Wi-Fi, invigorating shower, \n                                and indulgent toiletries. Some rooms offer captivating city or river views. Book now for an unforgettable stay!',
        address: '209, 30/4 Road, Xuan Khanh Ward, Ninh Kieu District, Can Tho, Viet Nam',
        lat:10.02491835290709, 
        long: 105.77427451534255,
        point: '9.1',
        popularity: 'Wonderful',
        reviews: '174',
        facilities: [
            `<i class="fas fa-swimmer"></i> Outdoor swimming pool`,
            `<i class="fas fa-spa"></i> Spa and wellness centre`,
            `<i class="fas fa-parking"></i> Free parking`,
            `<i class="fas fa-utensils"></i> 4 Restaurants`,
            `<i class="fas fa-dumbbell"></i> Fitness centre`,
            `<i class="fas fa-glass-martini-alt"></i> Bar`,
            `<i class="fas fa-coffee"></i> Fabulous breakfast`,
            `<i class="fas fa-shuttle-van"></i> Airport transfer service`,
            `<i class="fas fa-smoking-ban"></i> No Smoking Room`
        ],
        facebook: 'https://www.facebook.com/@SheratonCanTho',
        website: 'https://vn.sheratoncantho.com/?fbclid=IwY2xjawGFObhleHRuA2FlbQIxMAABHVm8UJHBT40luFBgF1n7GJbguLP4_-WuRAv6HJfGHdmxHK7HEVHp_5UlqA_aem_ZlV9It6YmGI6HDq2iM3WlA',
        phone: 'tel: +84292 3761 888',
        mail: 'mailto: vcasi.reservation@sheraton.com'
    },
    {
        id: 'hotel3',
        name: 'Muong Thanh Luxury Hotel',
        layoutPrice: '1,301,270 VND',
        roomType: [
            { roomId: "hotel3_room1", name: 'Single bed room', price: '950,000 VND' },
            { roomId: "hotel3_room2", name: 'Double bed room', price: '1,500,000 VND' },
            { roomId: "hotel3_room3", name: 'Family room', price: '3,000,000 VND' }
        ],
        mainImage: '../images/Hotel img/MuongThanh/MuongThanh.jpg',
        layoutAddress: "Ninh Kieu, CanTho",
        utilities: ['Breakfast included'],
        modalImages: [
            '../images/Hotel img/MuongThanh/MuongThanh_sub1.jpg',
            '../images/Hotel img/MuongThanh/MuongThanh_sub2.jpg',
            '../images/Hotel img/MuongThanh/MuongThanh_sub3.jpg',
            '../images/Hotel img/MuongThanh/MuongThanh_sub4.jpg'
        ],
        description: 'Experience ultimate luxury at Muong Thanh Luxury Can Tho Hotel, the only luxury hotel in the Mekong Delta. Unwind in refined rooms, relax in the spa center and outdoor pool, and immerse yourself in the essence of the region. \n                                Located in Cái Khế, Cần Thơ, this property offers a tranquil atmosphere and is close to local attractions, shopping, and dining options. Indulge in luxury with a stunning pool, private beach, and thrilling casino. Enjoy the \n                                rejuvenating steam room or embark on exciting tours. Immerse yourself in luxury with air conditioning, complimentary Wi-Fi, invigorating showers, and captivating views available in select rooms. Explore nearby landmarks such \n                                as Can Tho Beach, Ninh Kieu Wharf, and Ong Temple. Book now for an unforgettable stay!',
        address: 'Area E1, Cai Khe River, Cai Khe Ward, Ninh Kieu Distrist, Can Tho, Viet Nam',
        lat:10.042699979131122, 
        long:105.7902817508841,
        point: '7.8',
        popularity: 'Good',
        reviews: '150',
        facilities: [
            `<i class="fas fa-swimmer"></i> Outdoor swimming pool`,
            `<i class="fas fa-wifi"></i> Free wifi`,
            `<i class="fas fa-spa"></i> Spa and wellness centre`,
            `<i class="fas fa-parking"></i> Free parking`,
            `<i class="fas fa-utensils"></i> Restaurant`,
            `<i class="fas fa-dumbbell"></i> Fitness centre`,
            `<i class="fas fa-glass-martini-alt"></i> Bar`,
            `<i class="fas fa-coffee"></i> Breakfast`,
            `<i class="fas fa-shuttle-van"></i> Airport transder service`,
        ],
        facebook: 'https://www.facebook.com/cantho.muongthanh.vn',
        website: 'https://www.facebook.com/cantho.muongthanh.vn',
        phone: 'tel: +84292 3688 888',
        mail: 'mailto: salesgroup@cantho.muongthanh.vn'
    },
    {
        id: 'hotel4',
        name: 'Charmant Suites a Boutique Hotel',
        layoutPrice: '2,024,067 VND',
        roomType: [
            { roomId: "hotel4_room1", name: 'Single bed room', price: '950,000 VND' },
            { roomId: "hotel4_room2", name: 'Double bed room', price: '1,500,000 VND' },
            { roomId: "hotel4_room3", name: 'Family room', price: '3,000,000 VND' }
        ],
        mainImage: '../images/Hotel img/Charmant Suites/Charmant_Suites.jpg',
        layoutAddress: "Ninh Kieu, CanTho",
        utilities: ['Free cancellation', 'No prepayment needed'],
        modalImages: [
            '../images/Hotel img/Charmant Suites/Charmant_Suites_sub1.jpg',
            '../images/Hotel img/Charmant Suites/Charmant_Suites_sub2.jpg',
            '../images/Hotel img/Charmant Suites/Charmant_Suites_sub3.jpg',
            '../images/Hotel img/Charmant Suites/Charmant_Suites_sub4.jpg'
        ],
        description: "With a stay at Charmant Suites a Boutique Hotel Can Tho, you'll be centrally located in Can Tho, \n                                steps from Can Tho Museum and within a 5-minute walk of Ninh Kieu Park. This luxury hotel is 0.4 \n                                mi (0.6 km) from Luu Huu Phuoc Park and 1.1 mi (1.7 km) from Cai Khe Trade Center.",
        address: 'No.45, Ngo Quyen Street, Tan An, Ninh Kieu District, Can Tho, Viet Nam',
        lat: 10.034282622017159, 
        long: 105.78669754112684,
        point: '8.9',
        popularity: 'Fabulous',
        reviews: '200',
        facilities: [
            `<i class="fas fa-swimmer"></i> Outdoor swimming pool`,
            `<i class="fas fa-spa"></i> Spa and wellness centre`,
            `<i class="fas fa-parking"></i> Free parking`,
            `<i class="fas fa-utensils"></i> 3 Restaurants`,
            `<i class="fas fa-dumbbell"></i> Fitness centre`,
            `<i class="fas fa-glass-martini-alt"></i> Bar`,
            `<i class="fas fa-coffee"></i> Fabulous breakfast`,
            `<i class="fas fa-smoking-ban"></i> No Smoking Room`,
            `<i class="fas fa-wheelchair"></i> Facilities for Disabled Guests`
        ],
        facebook: 'https://www.facebook.com/CharmantSuitesHotel/',
        website: '',
        phone: 'tel: +84292 3762 789',
        mail: 'mailto: reservations@charmantsuites.com'
    },
    {
        id: 'hotel5',
        name: 'Riverside 1 Hotel',
        layoutPrice: '688,500 VND',
        roomType: [
            { roomId: "hotel5_room1", name: 'Single bed room', price: '950,000 VND' },
            { roomId: "hotel5_room2", name: 'Double bed room', price: '1,500,000 VND' },
            { roomId: "hotel5_room3", name: 'Family room', price: '3,000,000 VND' }
        ],
        mainImage: '../images/Hotel img/Riverside1/Riverside1.jpg',
        layoutAddress: "Ninh Kieu, CanTho",
        utilities: ['Free cancellation', 'No prepayment needed'],
        modalImages: [
            '../images/Hotel img/Riverside1/Riverside1_sub1.jpg',
            '../images/Hotel img/Riverside1/Riverside1_sub2.jpg',
            '../images/Hotel img/Riverside1/Riverside1_sub3.jpg',
            '../images/Hotel img/Riverside1/Riverside1_sub4.jpg'
        ],
        description: "Discover the charm of Riverside Boutique Hotel, situated in the tranquil area of Cái Khế, Cần Thơ. Perfect for two travelers seeking a peaceful retreat, this hotel offers a convenient location close to local attractions, shopping, and dining options. Enjoy the luxury of 24-hour check-in and indulge in delectable meals at the exquisite restaurant. Unwind in the air-conditioned rooms with complimentary WiFi and take in stunning views of the city or the outdoor surroundings. Immerse in local culture by exploring Can Tho Beach, Ninh Kieu Wharf, and the Can Tho Museum. Make your stay memorable at Riverside Boutique Hotel. ",
        address: 'No.38, Le Loi Street, Ninh Kieu District, Can Tho, Viet Nam',
        lat: 10.048709339459858, 
        long: 105.787607949034714,
        point: '8.6',
        popularity: 'Fabulous',
        reviews: '468',
        facilities: [
            `<i class="fas fa-utensils"></i> Restaurants`,
            `<i class="fas fa-people-roof"></i> Family room`,
            `<i class="fas fa-coffee"></i> Very Good breakfast`,
            `<i class="fas fa-smoking-ban"></i> No Smoking Room`,
            `<i class="fas fa-wifi"></i> Free wifi`,
            `<i class="fas fa-parking"></i> Free parking`,
        ],
        facebook: '',
        website: '',
        phone: 'tel: +84292 3653 838',
        mail: ''
    },
    {
        id: 'hotel6',
        name: 'Wink Hotel Can Tho',
        layoutPrice: '980,000 VND',
        roomType: [
            { roomId: "hotel5_room1", name: 'Single bed room', price: '950,000 VND' },
            { roomId: "hotel5_room2", name: 'Double bed room', price: '1,500,000 VND' },
            { roomId: "hotel5_room3", name: 'Family room', price: '3,000,000 VND' }
        ],
        mainImage: '../images/Hotel img/WinkHotel/WinkHotel.jpg',
        layoutAddress: "Ninh Kieu, CanTho",
        utilities: ['Late escape deal'],
        modalImages: [
            '../images/Hotel img/WinkHotel/WinkHotel_sub1.jpg',
            '../images/Hotel img/WinkHotel/WinkHotel_sub2.jpg',
            '../images/Hotel img/WinkHotel/WinkHotel_sub3.jpg',
            '../images/Hotel img/WinkHotel/WinkHotel_sub4.jpg'
        ],
        description: "The car parking and the Wi-Fi are always free, so you can stay in touch and come and go as you please. Strategically situated in Ninh Kieu Quay, allowing you access and proximity to local attractions and sights. Be sure to set some time aside to visit Binh Thuy Communal House as well as Can Tho Beach nearby. Rated with 4 stars, this high-quality property provides guests with access to restaurant, fitness center and outdoor pool on-site. ",
        address: 'No.14, Phan Dinh Phung Street, Tan An, Ninh Kieu District, Can Tho, Viet Nam',
        lat: 10.033247509138425, 
        long: 105.78664573739083,
        point: '8.8',
        popularity: 'Fabulous',
        reviews: '118',
        facilities: [
            `<i class="fas fa-utensils"></i> Restaurants`,
            `<i class="fas fa-people-roof"></i> Family room`,
            `<i class="fas fa-smoking-ban"></i> No Smoking Room`,
            `<i class="fas fa-wifi"></i> Free wifi`,
            `<i class="fas fa-parking"></i> Free parking`,
            `<i class="fas fa-swimmer"></i> Outdoor swimming pool`,
            `<i class="fas fa-dumbbell"></i> Fitness centre`,
            `<i class="fas fa-glass-martini-alt"></i> Bar`,
            `<i class="fas fa-coffee"></i> Very good breakfast`,
        ],
        facebook: 'https://www.facebook.com/winkcantho/',
        website: 'https://www.wink-hotels.com/?fbclid=IwY2xjawGZ1Q1leHRuA2FlbQIxMAABHXOx5cpuQyyNfMx0oSCcFTxv-TQ5Bg4VnqfbY8mH8ZzF7DDPOXFLXniKzA_aem_LMa-KjIgpLDq8Otdr9021w',
        phone: 'tel: +8428 2250 8530',
        mail: ''
    },
]

const restaurantData = [
    {
        id: 'restaurant1',
        name: 'Spirito Restaurant & Bar',
        layoutPrice: '2,564,103 VND',
        mainImage: '../images/Restaurants_img/Spirito Restaurant/Spirito_Restaurant.jpg',
        layoutAddress: "Cai Khe, CanTho",
        utilities: ['Free cancellation', 'International', 'Fusion'],
        modalImages: ['../images/Restaurants_img/Spirito Restaurant/Spirito_Restaurant_sub1.jpg',
            '../images/Restaurants_img/Spirito Restaurant/Spirito_Restaurant_sub2.jpg',
            '../images/Restaurants_img/Spirito Restaurant/Spirito_Restaurant_sub3.jpg',
            '../images/Restaurants_img/Spirito Restaurant/Spirito_Restaurant_sub4.jpg'],
        description: 'Spirito Restaurant & Bar is the ideal place to hang out with Friends in Can Tho, Mekong Delta, Vietnam. \n                                A spacious and elegant Restaurant in the HEART of CAN THO, in which to discover a modern aesthetic to \n                                enjoy our western and fusion cuisine along with our imported best wines and finest cocktails.',
        address: 'No.2, Nguyen Binh Khiem Street, An Hoi, Cai Khe District, Can Tho, Vietnam',
        lat: 10.042605627985846, 
        long: 105.78287016437716,
        point: '9.5',
        popularity: 'Wonderful',
        reviews: '60',
        facilities: [
            `<i class="fas fa-sun"></i> Outdoor seating`,
            `<i class="fas fa-door-closed"></i> Private Dining`,
            `<i class="fas fa-parking"></i> Parking available`,
            `<i class="fas fa-wheelchair"></i> Wheelchair Accessible`,
            `<i class="fas fa-wine-glass"></i> Serves Alcohol`,
            `<i class="fas fa-credit-card"></i> Accepts Credit Cards`,
            `<i class="fas fa-wifi"></i> Free wifi`,
            `<i class="fas fa-water"></i> Waterfront`
        ],
        openTime: "7:00 am - 12:00 am",
        priceRange: "2,564,103 VND - 25,641,026 VND",
        facebook: 'https://www.facebook.com/spirito.restaurant.bar',
        website: '',
        phone: 'tel: +84292 3633 377',
        mail: 'mailto: admin@spiritovn.com'
    },
    {
        id: 'restaurant2',
        name: 'Saravan Restaurant',
        layoutPrice: '200,000 VND',
        mainImage: '../images/Restaurants_img/Saravan Restaurant/Savaran_Restaurant.jpg',
        layoutAddress: "Ninh Kieu, CanTho",
        utilities: ['Free cancellation', 'Seafood', 'Asian', 'Healthy'],
        modalImages: ['../images/Restaurants_img/Saravan Restaurant/Savaran_Restaurant_sub1.jpg',
            '../images/Restaurants_img/Saravan Restaurant/Savaran_Restaurant_sub2.jpg',
            '../images/Restaurants_img/Saravan Restaurant/Savaran_Restaurant_sub3.jpg',
            '../images/Restaurants_img/Saravan Restaurant/Savaran_Restaurant_sub4.jpg'],
        description: 'Vietnamese and original Kmer fusion restaurant, enjoy the forgotten well-loved dishes from ancient times.\n                                Let the taste of our ancestors surprise you at a elegant dinner venue. Ideal for romantic settings and \n                                business lunch & dinners.',
        address: 'Floor 6 Sheraton Hotel, No.209, 30/4 Street, Ninh Kieu District, Can Tho, Vietnam',
        lat: 10.025784834369638, 
        long: 105.77365091436417, 
        point: '9.7',
        popularity: 'Wonderful',
        reviews: '120',
        facilities: [
            `<i class="fas fa-door-closed"></i>Private Dining`,
            `<i class="fas fa-parking"></i> Parking available`,
            `<i class="fas fa-users"></i> Family style`,
            `<i class="fas fa-utensils"></i> Table Service`,
            `<i class="fas fa-credit-card"></i> Accepts Credit Cards`,
            `<i class="fas fa-wifi"></i> Free wifi`,
            `<i class="fas fa-smoking-ban"></i> Non-smoking Restaurantt`,
            `<i class="fas fa-carrot"></i> Vegetarian Friendly`
        ],
        openTime: "11:30 am - 10:00 pm",
        priceRange: "2,564,103 VND - 25,641,026 VND",
        facebook: 'https://www.facebook.com/saravansheraton/?locale=vi_VN',
        website: '',
        phone: 'tel: +84292 3761 888',
        mail: ''
    },
    {
        id: 'restaurant3',
        name: 'Family Wine Can Tho',
        layoutPrice: '59,000 VND',
        mainImage: '../images/Restaurants_img/Family Wine/Family_Wine_CanTho.jpg',
        layoutAddress: "Ninh Kieu, Can Tho",
        utilities: ['Free cancellation', 'Italian', 'French', 'European'],
        modalImages: ['../images/Restaurants_img/Family Wine/Family_Wine_CanTho_sub1.jpg',
            '../images/Restaurants_img/Family Wine/Family_Wine_CanTho_sub2.jpg',
            '../images/Restaurants_img/Family Wine/Family_Wine_CanTho_sub3.jpg',
            '../images/Restaurants_img/Family Wine/Family_Wine_CanTho_sub4.jpg'],
        description: 'An exquisite European-style restaurant, graced with timeless neo-classical architecture, \n                                evokes an atmosphere of pure elegance and romance. Each dish is a masterpiece, crafted \n                                with unwavering dedication and artistry, promising an unforgettable dining experience with \n                                exceptional service, meticulously designed to delight you in every way.',
        address: 'No.55A, Nam Ky Khoi Nghia Street, An Hoi, Cai Khe District, Can Tho, Vietnam',
        lat: 10.032210360422376, 
        long: 105.78437585562867,
        point: '9.0',
        popularity: 'Wonderful',
        reviews: '86',
        facilities: [
            `<i class="fas fa-sun"></i> Outdoor seating`,
            `<i class="fas fa-door-closed"></i> Private Dining`,
            `<i class="fas fa-parking"></i> Parking available`,
            `<i class="fas fa-smoking-ban"></i> Non-smoking Restaurantt`,
            `<i class="fas fa-wine-glass"></i> Serves Alcohol`,
            `<i class="fas fa-coffee"></i> Brunch`,
            `<i class="fas fa-wifi"></i> Free wifi`
        ],
        openTime: "3:00 pm - 11:00 pm",
        priceRange: "2,564,103 VND - 25,641,026 VND",
        facebook: 'https://www.facebook.com/biavavang/',
        website: '',
        phone: 'tel: +8490 300 85 88',
        mail: 'mailto: admin@spiritovn.com'
    },
    {
        id: 'restaurant4',
        name: 'Sky Garden BBQ Food & Beer',
        layoutPrice: '15,000 VND',
        mainImage: '../images/Restaurants_img/Sky Garden/Sky_Garden_Restaurant.jpg',
        layoutAddress: "Ninh Kieu, Can Tho",
        utilities: ['Free cancellation',
            'Vietanamese',
            'Beer Restaurant',
            'European'],
        modalImages: ['../images/Restaurants_img/Sky Garden/Sky_Garden_Restaurant_sub1.jpg',
            '../images/Restaurants_img/Sky Garden/Sky_Garden_Restaurant_sub2.jpg',
            '../images/Restaurants_img/Sky Garden/Sky_Garden_Restaurant_sub3.jpg',
            '../images/Restaurants_img/Sky Garden/Sky_Garden_Restaurant_sub4.jpg'],
        description: 'Enjoy a memorable dining experience at our rooftop restaurant with stunning views of \n                                Ninh Kieu Quay and the Mekong River. Savor delicious dishes and refreshing beers with \n                                friends in a vibrant atmosphere. Join us for an unforgettable evening of great food, \n                                drinks, and breathtaking scenery!',
        address: 'No.26, Hai Ba Trung Street, Tan An, Ninh Kieu District, Can Tho, Vietnam',
        lat: 10.034563490286374, 
        long: 105.78857976622658,
        point: '8.0',
        popularity: 'Fabulous',
        reviews: '43',
        facilities: [
            `<i class="fas fa-sun"></i> Outdoor seating`,
            `<i class="fas fa-door-closed"></i> Private Dining`,
            `<i class="fas fa-parking"></i> Parking available`,
            `<i class="fas fa-smoking-ban"></i> Non-smoking Restaurantt`,
            `<i class="fas fa-wine-glass"></i> Serves Alcohol`,
            `<i class="fas fa-money-bill-wave"></i> Cash Only`,
            `<i class="fas fa-wifi"></i> Free wifi`
        ],
        openTime: "6:00 am - 2:00 pm",
        priceRange: "2,564,103 VND - 25,641,026 VND",
        facebook: 'https://www.facebook.com/@HaiSanGiangGheCanTho/',
        website: '',
        phone: 'tel: +8490 619 99 93',
        mail: 'mailto: lethanhgiang010188@gmail.com'
    },
    {
        id: 'restaurant5',
        name: 'Tomato Pad Thái',
        layoutPrice: '18,000 VND',
        mainImage: '../images/Restaurants_img/Tomato/Tomato.jpg',
        layoutAddress: "Ninh Kieu, Can Tho",
        utilities: ['Thailand',
            'Vietanamese',
            'Asian',
            'Chinese'],
        modalImages: ['../images/Restaurants_img/Tomato/Tomato_sub1.jpg',
            '../images/Restaurants_img/Tomato/Tomato_sub2.jpg',
            '../images/Restaurants_img/Tomato/Tomato_sub3.jpg',
            '../images/Restaurants_img/Tomato/Tomato_sub4.jpg'],
        description: 'Pad Thai Restaurant brings you the authentic flavors of Thailand with rich, enticing dishes. We are committed to using fresh ingredients, ensuring quality in every dish. At Pad Thai, you will enjoy true Thai cuisine in a cozy and welcoming atmosphere.',
        address: 'No.54, Nam Ky Khoi Nghia Street, An Hoi, Ninh Kieu District, Can Tho, Vietnam',
        lat: 10.032412356272626, 
        long: 105.78430310855526,
        point: '9.0',
        popularity: 'Wonderful',
        reviews: '351',
        facilities: [
            `<i class="fas fa-sun"></i> Outdoor seating`,
            `<i class="fas fa-wine-glass"></i> Serves Alcohol`,
            `<i class="fas fa-money-bill-wave"></i> Cash Only`,
            `<i class="fas fa-wifi"></i> Free wifi`,
            `<i class="fas fa-carrot"></i> Vegetarian Friendly`,
            `<i class="fas fa-credit-card"></i> Accepts Credit Cards`,
            `<i class="fas fa-wallet"></i> Digital Payments`,
        ],
        openTime: "9:00 am - 10:00 pm",
        priceRange: "18,000 VND - 87,000 VND",
        facebook: 'https://www.facebook.com/tomatopadthai',
        website: '',
        phone: 'tel: +8494 420 47 41',
        mail: ''
    },
    {
        id: 'restaurant6',
        name: 'Bo Tung Xeo Nu Nhi Hong',
        layoutPrice: '25.641 VND',
        mainImage: '../images/Restaurants_img/Botungxeonunhihong/Botungxeonunhihong.jpg',
        layoutAddress: "Binh Thuy, Can Tho",
        utilities: ['Steakhouse',
            'Vietanamese',
            'Asian',
            'Grill',
            'Barbecue'],
        modalImages: ['../images/Restaurants_img/Botungxeonunhihong/Botungxeonunhihong_sub1.jpg',
            '../images/Restaurants_img/Botungxeonunhihong/Botungxeonunhihong_sub2.jpg',
            '../images/Restaurants_img/Botungxeonunhihong/Botungxeonunhihong_sub3.jpg',
            '../images/Restaurants_img/Botungxeonunhihong/Botungxeonunhihong_sub4.jpg'],
        description: 'Our restaurant is the perfect destination for food lovers seeking diverse cuisines, from flavorful steaks and smoky barbecue to unique Asian and Vietnamese dishes. With a cozy atmosphere and casual pub-style vibe, we provide quality meals and memorable experiences. Come visit us and savor the amazing flavors of grilled dishes, pub fare, and delicious Vietnamese specialties!',
        address: 'No.202, Vo Van Kiet Street, An Thoi Ward, Binh Thuy District, Can Tho, Vietnam',
        lat: 10.048588874994689, 
        long: 105.75843264698206,
        point: '9.0',
        popularity: 'Wonderful',
        reviews: '84',
        facilities: [
            `<i class="fas fa-leaf"></i> Gluten free option`,
            `<i class="fas fa-parking"></i> Parking available`,
            `<i class="fas fa-sun"></i> Outdoor seating`,
            `<i class="fas fa-wine-glass"></i> Serves Alcohol`,
            `<i class="fas fa-money-bill-wave"></i> Cash Only`,
            `<i class="fas fa-wifi"></i> Free wifi`,
            `<i class="fas fa-credit-card"></i> Accepts Credit Cards`,
            '<i class="fas fa-wheelchair"></i> Wheelchair Accessible'
        ],
        openTime: "9:00 am - 11:00 pm",
        priceRange: "25.641 VND - 256.410 VND",
        facebook: 'https://www.facebook.com/Qu%C3%A1n-B%C3%B2-T%C3%B9ng-X%E1%BA%BBo-N%E1%BB%AF-Nhi-H%E1%BB%93ng-338089156573130/',
        website: '',
        phone: 'tel: +84 710 6539 888',
        mail: ''
    }
]